name: msig_assignment_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dartz: ^0.10.1
  drift: ^2.15.0
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  path: ^1.8.3
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  drift_sqflite: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
